name: 'php-code-sniffer-standard'
services:
    php74:
        type: 'php:7.4'
        xdebug: true
        overrides:
            environment:
                PHP_IDE_CONFIG: 'serverName=appserver'
                XDEBUG_TRIGGER: '1'
    php80:
        type: 'php:8.0'
        xdebug: true
        overrides:
            environment:
                PHP_IDE_CONFIG: 'serverName=appserver'
                XDEBUG_TRIGGER: '1'
    php81:
        type: 'php:8.1'
        xdebug: true
        overrides:
            environment:
                PHP_IDE_CONFIG: 'serverName=appserver'
                XDEBUG_TRIGGER: '1'
tooling:
    phpunit:
        cmd:
            -   php74: 'vendor/bin/phpunit'
            -   php80: 'vendor/bin/phpunit'
            -   php81: 'vendor/bin/phpunit'
