<?php

declare(strict_types=1);

namespace MethodPerClassLimitBad;

class TooManyMethods
{
    public function method1(): void
    {
    }

    public function method2(): void
    {
    }

    public function method3(): void
    {
    }

    public function method4(): void
    {
    }

    public function method5(): void
    {
    }

    public function method6(): void
    {
    }

    public function method7(): void
    {
    }

    public function method8(): void
    {
    }

    public function method9(): void
    {
    }

    public function method10(): void
    {
    }

    public function method11(): void
    {
    }
}
